cas:
  enable: false
  expiry: 3600 #one hour
  url: https://localhost:8888
  login_path: '/cas/api-login'
  logout_path: '/cas/api-logout'
lms:
  enable: false
  account_id: 1
  oauth_token: BWByYxU7pnqLi6lWICmGcYGn66xuaZEAsImJgLgUsmj3hSkoTK5UzCFesmZUdQDx
  api_root_url: https://192.168.1.40/api/v1

