cas:
  enable: false
  expiry: 28800 #8 hour
  url: https://cas.arrivu.corecloud.com/
  login_path: '/cas/api-login'
  logout_path: '/cas/api-logout'   
lms:
  enable: false
  account_id: 4
  #oauth_token: 88n7pFHCredVJLG3MiBU2Oidp6D4uYmpsxz8hG33RNhrrVKbJGsluL0tSdV7ydW2
  oauth_token: dOe1y7fbvJx6ytwkcCinrmutmTkobhYe6xo6gf2wtWF38lEZt1J3ffQcDflAFDIe
  root_url: https://lms.arrivu.corecloud.com/
  course_url_path: courses/
  api_root_url: https://lms.arrivu.corecloud.com/api/v1
  logout_path: logout
mailserver:
  address: smtp.gmail.com
  port: 587
  domain: localhost:3000
  user_name: beaconlms@gmail.com
  password: beaconlms123$
admin_mail:
  to: beaconlms@gmail.com
payment_gateway:
  enable: false
  merchant_id: "M_blahpache_5678"
  work_key: "6abc0ty90e0v7jk9hj"
  ccavenue_account: "test123"
invoices:
  notes: "Thank you for your enrollment!"
exception_notifer:
  email_prefix: "[Beacon Exception Notifier]"
  sender_address: "beaconlms@gmail.com"
  exception_recipients: "beaconlms@gmail.com"
omniauth:
  facebook_key: "553752584663567"
  facebook_secret: "06f0e8213795d3896e809b8d8eda9332"
  linkedin_key: "31azcdigi8tt"
  linkedin_secret: "OKd1hmuJoNOg9J2g"
  google_oauth2_key: "928801233183"
  google_oauth2_secret: "-nMQ0dEfcaBITxzwYHZPQ3v-"
